apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 80
    name: http
  selector:
    name: voting-app-pod
    app: demo-voting-app